# Generated by Django 6.0 on 2025-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
