# Generated by Django 6.0 on 2025-12-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_userprofile_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], default='dummy', max_length=20),
        ),
    ]
